Add fee-oracle to local setup
sygmaprotocol/sygma-relayer pull request #11
Opened 2022-09-16 11:13 UTC by nmlinaric

## Description
Add fee-oracle to local setup

## Related Issue Or Context
Closes: #7 

## How Has This Been Tested? Testing details.
Manual tests, e2e tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-09-21 13:09 UTC, mpetrun5 requested changes

2022-09-21 13:09 UTC, mpetrun5 commented on e2e/evm/evm_test.go
> +	tokenId := big.NewInt(int64(rand.Intn(1000)))
@nmlinaric Can you please fix this?

2022-09-22 09:01 UTC, mpetrun5 approved these changes

2022-09-22 12:34 UTC, MakMuftic approved these changes

2022-09-22 12:35 UTC, merged