Encode aes encrypted data to hex
sygmaprotocol/sygma-relayer pull request #16
Opened 2022-09-27 16:19 UTC by mpetrun5

Encode aes encrypted data to hex to match format on online calculator.

## Description

## Related Issue Or Context

Closes: #<issue>

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [x] I have updated the documentation locally and in docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-09-27 16:26 UTC, MakMuftic approved these changes

2022-09-27 16:45 UTC, P1sar requested changes

2022-09-27 16:45 UTC, P1sar commented on topology/encryption.go
> +var IV = []byte("1234567812345678")
IV should be different for every new encryption

2022-09-27 16:45 UTC, P1sar commented on topology/encryption.go
> +var IV = []byte("1234567812345678")
`IV reused with CTR can lead to trivial decryptions. `

2022-09-28 09:23 UTC, MakMuftic approved these changes
LGTM, added a short description on this encryption process/format inside our devnet notion page

2022-09-28 11:16 UTC, merged