chore: bump packages
sygmaprotocol/sygma-relayer pull request #236
Opened 2023-10-31 18:01 UTC by mj52951

Bumping packages so that code can be refactored to use sygma-core

2023-11-02 11:54 UTC, mpetrun5 requested changes
Please fix tests and then we'll merge this first and then we can go into event handlers

2023-11-02 11:54 UTC, mpetrun5 commented on go.mod
>  	github.com/centrifuge/go-substrate-rpc-client v2.0.0+incompatible
Can you please references to this and remove this dependecy as well?
For reference all imports that are `.../go-substrate-rpc-client` should go to the v4 version

2023-12-06 17:39 UTC, mj52951 commented
Checks are not passing because dependency review detected a vulnerable package. References and more info about it could be found here: https://github.com/advisories/GHSA-v9jh-j8px-98vq 

Geth team response is that because the GraphQL feature is an option, it is out of scope of the Ethereum Bug Bounty program. Also, the team has no intention of fixing this issue. (https://blog.mevsec.com/posts/geth-dos-with-graphql/#5-ethereum-response)

2023-12-08 11:55 UTC, mpetrun5 approved these changes

2023-12-08 11:55 UTC, merged