chore: Add keygen CLI
sygmaprotocol/sygma-relayer pull request #278
Opened 2024-05-14 10:54 UTC by mj52951

Added a CLI command that generates ECDSA keypair and prints out the private key.

2024-05-14 11:43 UTC, mpetrun5 requested changes

2024-05-14 11:43 UTC, mpetrun5 commented on cli/keygen/generateKey.go
> +	fmt.Printf("Private key: %s\n", privHex)
Might as well print out the pubkey as well.

2024-05-14 12:48 UTC, MakMuftic requested changes
@mj52951 Can we also expand `/docs` with docs for new CLI command?

2024-05-20 14:55 UTC, mpetrun5 approved these changes

2024-05-20 16:40 UTC, merged