chore: fix typos
sygmaprotocol/sygma-relayer pull request #313
Opened 2024-06-24 13:11 UTC by tcar121293

fix typos
## Description
fix typos
make small performance upgrade
## Related Issue Or Context

Closes: https://veridise.notion.site/Typos-and-incorrect-comments-53799628680a40af8acea16ef1470e28

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-06-24 13:15 UTC, mpetrun5 requested changes

2024-06-24 13:15 UTC, mpetrun5 commented on tss/frost/common/util.go
> +	// Sort the idSlice
I think this is unnecessary.

2024-06-24 13:15 UTC, mpetrun5 commented on chains/btc/listener/event-handlers.go
> -	// ResourceID used to find address of handler to be used for deposit
Maybe just update to something relevant

2024-07-10 10:24 UTC, mpetrun5 approved these changes

2024-07-10 10:42 UTC, nmlinaric approved these changes

2024-07-10 12:02 UTC, merged