chore: add btc deposit format explanation
sygmaprotocol/sygma-relayer pull request #318
Opened 2024-06-25 13:30 UTC by tcar121293

add btc deposit format explanation
## Description

## Related Issue Or Context

Closes: https://veridise.notion.site/Unclear-BTC-transaction-assumptions-6b182f76f4c14f9ea967a83e97e532df

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2024-06-25 13:33 UTC, mpetrun5 requested changes

2024-06-25 13:33 UTC, mpetrun5 commented on docs/general/BTC-Deposit-Format.md
> +- Only outputs with script types of `WitnessV0KeyHash` are considered for the amount calculation.
I think this is wrong.

2024-06-25 13:33 UTC, mpetrun5 commented on docs/general/Arhitecture.md
> +- **[BTC Deposit Format](/docs/general/BTC-Deposit-Format.md)** - BTC deposit format explanation
Create a meaningful folder for transaction information.

2024-07-10 10:46 UTC, nmlinaric approved these changes

2024-07-10 12:07 UTC, mpetrun5 approved these changes

2024-07-10 12:08 UTC, merged