feat: process permissionless generic  messages sequentially
sygmaprotocol/sygma-relayer pull request #41
Opened 2022-11-08 15:35 UTC by mpetrun5

This PR creates a custom deposit handler that separates permisionless generic messages and processes them one by one to prevent gas limit abuse.

## Description

## Related Issue Or Context

Closes: #35 

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [x] I have updated the documentation locally and in docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-11-09 14:42 UTC, MakMuftic requested changes

2022-11-09 14:42 UTC, MakMuftic commented on chains/evm/listener/event-handler_test.go
> +func (s *DepositHandlerTestSuite) Test_HandleDepositPanis_ExecutionContinues() {
```suggestion
func (s *DepositHandlerTestSuite) Test_HandleDepositPanics_ExecutionContinues() {
```

2022-11-10 13:10 UTC, MakMuftic approved these changes

2022-11-10 13:53 UTC, nmlinaric approved these changes

2022-11-16 13:00 UTC, mpetrun5 commented on chains/evm/listener/event-handler.go
> +type DepositHandler interface {
You are right. It was named the same so I didn't use it, but I forgot it will be namespaced so it doesn't matter.
Will use that.

2022-11-16 13:16 UTC, P1sar approved these changes

2022-11-22 14:42 UTC, MakMuftic approved these changes

2022-11-22 14:45 UTC, merged