feat:  Implement deposit(fungibleTransfer) event handler
sygmaprotocol/sygma-relayer pull request #55
Opened 2022-12-05 08:29 UTC by tcar121293

Implement deposit(fungibleTransfer) event handler
## Description
Added Deposit struct
Added deposit handler function and deposit handler registration functionality
Added unit tests

## Related Issue Or Context

Closes: #48 

## How Has This Been Tested? Testing details.
Unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation

## Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in docs.
- [x] I have added tests to cover my changes.
- [x] I have ensured that all the checks are passing and green, I've signed the CLA bot

2022-12-05 14:50 UTC, mpetrun5 requested changes

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/deposit-handler.go
> +	// @dev
'@dev' ?

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/deposit-handler.go
> +	if 64+recipientAddressLength.Int64() < int64(len(calldata)) {
I don't think this is currently relevant as we don't use this

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/events.go
> +	SenderAddress       []byte
Why is this []byte ?

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/handlers.go
> +		func(d Deposit) {
This was done on core so it had recover() in case the HandleDeposit throwed a panic (which it did if some data was malformed)

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/handlers_test.go
> +func (s *DepositHandlerTestSuite) Test_SuccessfulHandleDeposit() {
Test unsuccessfull and panic deposit.

2022-12-05 14:50 UTC, mpetrun5 commented on chains/substrate/events/deposit-handler.go
> +func (e *SubstrateDepositHandler) RegisterDepositHandler(transferType message.TransferType, handler DepositHandlerFunc) {
Test for this and HandleDeposit would be appreciated

2022-12-07 11:29 UTC, mpetrun5 approved these changes

2022-12-07 14:49 UTC, P1sar approved these changes

2022-12-08 06:45 UTC, merged